language: php

php:
  # - 5.6
  - 7.0
  - 7.1
  - 7.2
  - nightly

matrix:
  allow_failures:
    - php: nightly

before_script:
  - composer selfupdate
  - composer install --dev --prefer-dist

script:
  - ./vendor/bin/phpunit --coverage-clover build/logs/clover.xml

# after_success:
#   - ./vendor/bin/test-reporter --coverage-report build/logs/clover.xml